name: wohlig devops test
 
on:
  push:
    branches:
      - 'uat'
 
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN100 }}
 
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Javed-Patel-wohlig/test-gitops.git  
          token: ${{ secrets.TOKEN100 }} 
          ref: main                  
          path: test-gitops
      - name: Update count in file
        run: |
          git init
          git config --global user.email "javed.patel@wohlig.com"
          git config --global user.name "Javed-Patel-wohlig"
          git pull
          cd test-gitops
          count=$(grep -oP 'my commit count is : \K\d+' count.txt)
          echo $((count + 50)) > count.txt
          git add .
          git commit -m "updated the count"
 
          git status
 
          git push --set-upstream origin main
 
          git status
      
